CREATE SCHEMA `crud`;

CREATE TABLE produtos (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    valor FLOAT NOT NULL,
    PRIMARY KEY (id)
);